#!/bin/bash
### INSTALACION
sudo hostnamectl set-hostname ldapserver.micentro.edu
sudo nano /etc/hosts ->
127.0.1.1       ldapserver.micentro.edu
## END##

sudo apt update; sudo apt upgrade -y
sudo apt install slapd ldap-utils -y
sudo dpkg-reconfigure slapd
 - No omitir config.
 - Organización: micentro
 - Si Purgar paquete LDAP
 - Si mover base de datos antigua

### COMANDOS
sudo slapcat
sudo ldapadd -x -D cn=admin,dc=micentro,dc=edu -W -f ou.ldif 
sudo slappasswd
ldapsearch -xLLL -b "dc=micentro,dc=edu" uid=khalid sn givenName cn
ldapsearch -xLLL -b "dc=micentro,dc=edu" uid=* sn givenName cn
sudo ldapmodify -x -D cn=admin,dc=micentro,dc=edu -W -f cambios.ldif 
sudo ldapdelete -x -W -D 'cn=admin,dc=micentro,dc=edu' "uid=jaime,ou=informatica,dc=micentro,dc=edu"


### OU.LDIF
dn: ou=informatica,dc=micentro,dc=edu
objectClass: top
objectClass: organizationalUnit
ou: informatica

### GRP.LDIF
dn: cn=alumnos,ou=informatica,dc=micentro,dc=edu
objectClass: top
objectClass: posixGroup
gidNumber: 10000
cn: informatica

### USR.LDIF
dn: uid=jaime,ou=informatica,dc=micentro,dc=edu
objectClass: top
objectClass: posixAccount
objectClass: inetOrgPerson
objectClass: person
cn: jaime
uid: jaime
ou: informatica
uidNumber: 2001
gidNumber: 10000
homeDirectory: /home/jaime
loginShell: /bin/bash
userPassword: jaime
sn: martin
mail: jaime@micentro.edu
givenName: jaime

### CAMBIOS.LDIF
dn: uid=jaime,ou=informatica,dc=micentro,dc=edu
changetype: modify
replace: mail
mail: jaimemargar@micentro.edu

### INSTALACION CLIENTE
sudo apt-get install libnss-ldap libpam-ldap ldap-utils -y
En configuracion -> 
* URL: ldap://193.168.1.220
* dc=micentro,dc=edu
* LDAP version: 3
* Make local database: Yes
* Require login: No
* cn=admin,dc=micentro,dc=edu

sudo nano /etc/nsswitch.conf ->
# /etc/nsswitch.conf
#
# Example configuration of GNU Name Service Switch functionality.
# If you have the `glibc-doc-reference' and `info' packages installed, try:
# `info libc "Name Service Switch"' for information about this file.

passwd:         files ldap   
group:          files ldap   
shadow:         files ldap
gshadow:        files

##END##


sudo nano /etc/pam.d/common-session ->
# and here are more per-package modules (the "Additional" block)
session required        pam_unix.so
session optional                        pam_ldap.so
session optional        pam_systemd.so
session optional        pam_mkhomedir.so skel=/etc/skel umask=077
# end of pam-auth-update config

## END ##





### Comandos Cliente
# En caso de equivocarse en la configuración del LDAP
sudo dpkg-reconfigure ldap-auth-config
# Coje usuarios de LDAP y maquina local
sudo getent passwd
# ldap search en cliente
ldapsearch -x -H ldap://193.168.1.220 -b "dc=micentro,dc=edu"
# Meterse en usuario de ldap
sudo su - khalid



### Instalacion sesión gráfica
sudo apt install nslcd
sudo reboot

