#!/bin/bash
sudo apt-get update
sudo apt install samba
sudo systemctl status smbd
sudo nano /etc/samba/smb.conf ->
[global]

## Browsing/Identification ###

# Change this to the workgroup/NT-domain name your Samba server will part of
   workgroup = WORKGROUP
   netbios name = server
   secuity = user
   proxy = no
   map to guest = bad user

# server string is the equivalent of the NT Description field
   server string = %h server (Samba, Ubuntu)

#### Networking ####

# The specific set of interfaces / networks to bind to
# This can be either the interface name or an IP address/netmask;
# interface names are normally preferred
;   interfaces = 127.0.0.0/8 enp0s19

# ...En el final…


# Windows clients look for this share name as a source of downloadable
# printer drivers
[print$]
   comment = Printer Drivers
   path = /var/lib/samba/printers
   browseable = yes
   read only = yes
   guest ok = no
# Uncomment to allow remote administration of Windows print drivers.
# You may need to replace 'lpadmin' with the name of the group your
# admin users are members of.
# Please note that you also need to set appropriate Unix permissions
# to the drivers directory for these users to have write rights in it
;   write list = root, @lpadmin


[public]
   path = /samba/public
   browseable: yes
   guest ok = yes
   guest only = yes
   read only = no
   force user = nobody
   force create mode = 0777
   force directory mode = 0777
## END ##


sudo systemctl restart smbd
sudo mkdir -p /samba/public
sudo mkdir -p /samba/public
sudo chown -R nobody:nogroup /samba/public/
sudo chmod -R 0775 /samba/public/
sudo chgrp sambashare /samba/public/
sudo systemctl restart smbd

